### PR TITLE
Create / update consistent bpr for all repos

### PR DESCRIPTION
**Pull request by netomi**
This fixes also #4 .

For the cdt repo, I changed the pattern from * to the main branch only but the cdt_* branches could also be included?

### CODE REVIEW

**Review by jonahgraham — APPROVED** [review]

**Comment by jonahgraham** [comment]
For eclipse-cdt org repos you can make it for all branches as the flow recommends not to push private branches to the repo.

**Comment by netomi** [comment]
so the pattern should be changed to * for all repos?

**Comment by jonahgraham** [comment]
Yes please.

**Comment by netomi** [comment]
pushed commit to apply bpr to all branches in 91611eb0e9dc0888ff27af0c2ef553112f995830

**Pull request merged**
